/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Part } from "./Part";
import { PartCountArgs } from "./PartCountArgs";
import { PartFindManyArgs } from "./PartFindManyArgs";
import { PartFindUniqueArgs } from "./PartFindUniqueArgs";
import { CreatePartArgs } from "./CreatePartArgs";
import { UpdatePartArgs } from "./UpdatePartArgs";
import { DeletePartArgs } from "./DeletePartArgs";
import { ModificationFindManyArgs } from "../../modification/base/ModificationFindManyArgs";
import { Modification } from "../../modification/base/Modification";
import { CarModel } from "../../carModel/base/CarModel";
import { PartCreateInput } from "./PartCreateInput";
import { PartService } from "../part.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Part)
export class PartResolverBase {
  constructor(
    protected readonly service: PartService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Part",
    action: "read",
    possession: "any",
  })
  async _partsMeta(
    @graphql.Args() args: PartCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Part])
  @nestAccessControl.UseRoles({
    resource: "Part",
    action: "read",
    possession: "any",
  })
  async parts(@graphql.Args() args: PartFindManyArgs): Promise<Part[]> {
    return this.service.parts(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Part, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Part",
    action: "read",
    possession: "own",
  })
  async part(@graphql.Args() args: PartFindUniqueArgs): Promise<Part | null> {
    const result = await this.service.part(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Part)
  @nestAccessControl.UseRoles({
    resource: "Part",
    action: "create",
    possession: "any",
  })
  async createPart(@graphql.Args() args: CreatePartArgs): Promise<Part> {
    return await this.service.createPart({
      ...args,
      data: {
        ...args.data,

        carModel: args.data.carModel
          ? {
              connect: args.data.carModel,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Part)
  @nestAccessControl.UseRoles({
    resource: "Part",
    action: "update",
    possession: "any",
  })
  async updatePart(@graphql.Args() args: UpdatePartArgs): Promise<Part | null> {
    try {
      return await this.service.updatePart({
        ...args,
        data: {
          ...args.data,

          carModel: args.data.carModel
            ? {
                connect: args.data.carModel,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Part)
  @nestAccessControl.UseRoles({
    resource: "Part",
    action: "delete",
    possession: "any",
  })
  async deletePart(@graphql.Args() args: DeletePartArgs): Promise<Part | null> {
    try {
      return await this.service.deletePart(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Modification], { name: "modifications" })
  @nestAccessControl.UseRoles({
    resource: "Modification",
    action: "read",
    possession: "any",
  })
  async findModifications(
    @graphql.Parent() parent: Part,
    @graphql.Args() args: ModificationFindManyArgs
  ): Promise<Modification[]> {
    const results = await this.service.findModifications(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => CarModel, {
    nullable: true,
    name: "carModel",
  })
  @nestAccessControl.UseRoles({
    resource: "CarModel",
    action: "read",
    possession: "any",
  })
  async getCarModel(@graphql.Parent() parent: Part): Promise<CarModel | null> {
    const result = await this.service.getCarModel(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => PartCreateInput)
  async CreatePart(
    @graphql.Args()
    args: PartCreateInput
  ): Promise<PartCreateInput> {
    return this.service.CreatePart(args);
  }
}
