/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ModificationService } from "../modification.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ModificationCreateInput } from "./ModificationCreateInput";
import { Modification } from "./Modification";
import { ModificationFindManyArgs } from "./ModificationFindManyArgs";
import { ModificationWhereUniqueInput } from "./ModificationWhereUniqueInput";
import { ModificationUpdateInput } from "./ModificationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ModificationControllerBase {
  constructor(
    protected readonly service: ModificationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Modification })
  @nestAccessControl.UseRoles({
    resource: "Modification",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createModification(
    @common.Body() data: ModificationCreateInput
  ): Promise<Modification> {
    return await this.service.createModification({
      data: {
        ...data,

        part: data.part
          ? {
              connect: data.part,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        dateModified: true,
        description: true,
        id: true,

        part: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Modification] })
  @ApiNestedQuery(ModificationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Modification",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async modifications(@common.Req() request: Request): Promise<Modification[]> {
    const args = plainToClass(ModificationFindManyArgs, request.query);
    return this.service.modifications({
      ...args,
      select: {
        createdAt: true,
        dateModified: true,
        description: true,
        id: true,

        part: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Modification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Modification",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async modification(
    @common.Param() params: ModificationWhereUniqueInput
  ): Promise<Modification | null> {
    const result = await this.service.modification({
      where: params,
      select: {
        createdAt: true,
        dateModified: true,
        description: true,
        id: true,

        part: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Modification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Modification",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateModification(
    @common.Param() params: ModificationWhereUniqueInput,
    @common.Body() data: ModificationUpdateInput
  ): Promise<Modification | null> {
    try {
      return await this.service.updateModification({
        where: params,
        data: {
          ...data,

          part: data.part
            ? {
                connect: data.part,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          dateModified: true,
          description: true,
          id: true,

          part: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Modification })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Modification",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteModification(
    @common.Param() params: ModificationWhereUniqueInput
  ): Promise<Modification | null> {
    try {
      return await this.service.deleteModification({
        where: params,
        select: {
          createdAt: true,
          dateModified: true,
          description: true,
          id: true,

          part: {
            select: {
              id: true,
            },
          },

          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Post("/modification")
  @swagger.ApiOkResponse({
    type: ModificationCreateInput,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async CreateModification(
    @common.Body()
    body: ModificationCreateInput
  ): Promise<ModificationCreateInput> {
    return this.service.CreateModification(body);
  }
}
